// src/app/divider/divider.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-divider',
  templateUrl: './divider.component.html',
  styleUrls: ['./divider.component.less']
})
export class DividerComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}

<div class="divider">
  <div data-svg-drawing="yes" class="zigzag large clearfix ">
    <svg xml:space="preserve" viewBox="0 0 69.172 14.975" width="37" height="28" y="0px" x="0px" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" version="1.1"><path d="M1.357,12.26 10.807,2.81 20.328,12.332 29.781,2.879 39.223,12.321 48.754,2.79 58.286,12.321 67.815,2.793 " style="stroke-dasharray: 93.9851, 93.9851; stroke-dashoffset: 0;"></path>
    </svg>
  </div>
</div>

// components/divider.tsx
import React from "react";

export default function Divier() {
  return (
    <div className="divider">
      <div data-svg-drawing="yes" className="zigzag large clearfix ">
        <svg
          xmlSpace="preserve"
          viewBox="0 0 69.172 14.975"
          width="37"
          height="28"
          y="0px"
          x="0px"
          xmlnsXlink="http://www.w3.org/1999/xlink"
          xmlns="http://www.w3.org/2000/svg"
          version="1.1"
        >
          <path
            d="M1.357,12.26 10.807,2.81 20.328,12.332 29.781,2.879 39.223,12.321 48.754,2.79 58.286,12.321 67.815,2.793 "
            style={{ strokeDasharray: "93.9851, 93.9851", strokeDashoffset: 0 }}
          ></path>
        </svg>
      </div>
    </div>
  );
}
