// pages/education.tsx
import Divier from "../components/divider";
import Title from "../components/title";

function Education() {
  return (
    <section id="education" className="bgWhite ofsInBottom">
      <div className="expertise">
        <Title title="Education" />
        <div className="content">
          <div className="block-content">
            <div className="timeline education">
              <div className="row">
                <div className="col-md-12">
                  <div className="exp-holder margTop">
                    <div className="exp">
                      <div className="hgroup">
                        <h4>
                          {" "}
                          Ph.D. Network Engineering&nbsp; [ 2019 - present ]
                        </h4>
                        <h6>
                          <i className="fas fa-thumbtack"></i>
                          <b className="bold">
                            <a
                              className="gpacolor"
                              href="http://aut.ac.ir/aut/"
                            >
                              Amirkabir University of Technology
                            </a>
                          </b>
                          , Tehran, Iran
                        </h6>
                      </div>
                      <br />
                    </div>
                    <div className="exp">
                      <div className="hgroup">
                        <h4>
                          {" "}
                          M.Sc. Network Engineering&nbsp; [ 2017 - 2019 ]
                        </h4>
                        <h6>
                          <i className="fas fa-thumbtack"></i>
                          <b className="bold">
                            <a
                              className="gpacolor"
                              href="http://aut.ac.ir/aut/"
                            >
                              Amirkabir University of Technology
                            </a>
                          </b>
                          , Tehran, Iran
                        </h6>
                      </div>
                      <br />
                    </div>
                    <div className="exp">
                      <div className="hgroup">
                        <h4>
                          {" "}
                          B.Sc. Computer Engineering ( Software Engineering
                          )&nbsp; [ 2013 - 2017 ]
                        </h4>
                        <h6>
                          <i className="fas fa-thumbtack"></i>
                          <b className="bold">
                            <a
                              className="gpacolor"
                              href="http://aut.ac.ir/aut/"
                            >
                              Amirkabir University of Technology
                            </a>
                          </b>
                          , Tehran, Iran
                        </h6>
                      </div>
                      <br />
                    </div>
                    <div className="exp">
                      <div className="hgroup">
                        <h4>
                          High School Diploma in Mathematics and Physics [ 2009
                          - 2013 ]
                        </h4>
                        <h6>
                          <i className="fas fa-thumbtack"></i>
                          <b className="gpacolor">
                            {" "}
                            Energy Atomic High School
                          </b>{" "}
                          , Tehran, Iran
                        </h6>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div className="button margTop ofsInTop tCenter">
          <Divier />
        </div>
      </div>
    </section>
  );
}

export default Education;

// src/app/sections/education/education.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-education',
  templateUrl: './education.component.html',
  styleUrls: ['./education.component.less']
})
export class EducationComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}

<!--Education Tab-->
<section id="education" class="bgWhite ofsInBottom">
  <!--education -->
  <div class="expertise">
    <!--Education Main title-->
    <app-main-title title="Education"></app-main-title>
    <!--End main title-->
    <!--Content-->
    <div class="content">
      <div class="block-content">
        <!--Timeline-->
        <div class="timeline education">
          <!--Row-->
          <div class="row">
            <div class="col-md-12">

              <!--Education holder-->
              <div class="exp-holder margTop">
                <!--Education-->
                <div class="exp">
                  <div class="hgroup">
                    <h4> Ph.D. Network Engineering&nbsp; [ 2019 - present ]</h4>
                    <h6><i class="fas fa-thumbtack"></i><b class="bold"><a class="gpacolor" href="http://aut.ac.ir/aut/">Amirkabir University of Technology</a></b>, Tehran, Iran (<a href="http://www.usnews.com/education/best-global-universities/amirkabir-university-of-technology-506266" class="gpacolor">Ranked 85th in Computer Science [U.S. News])</a></h6>
                  </div>
                  <p class="tab"><b>GPA</b> of total: <b class="gpacolor">[ 18.77 / 20 ]</b></p>
                  <br>
                  <!--
                    <div class="hgroup tab">
                    <h6 class="tab"><i></i><b>Selected Courses:</b><br>
                    <ul class="two-col-special">
                    <li><b>Foundations of Data Mining</b> : [17.6/20]</li>
                    <li><b>Information Technology Project Management</b> : [19.75/20]</li>
                    <li><b>Engineering Mathematics</b> : [17.6/20]</li>
                    <li><b>Special Topics in Hardware</b> : [19.4/20]</li>
                    <li><b>Internet Engineering</b> : [16.5/20]</li>
                    <li><b>Software Engineering (II)</b> : [16.75/20]</li>
                    <li><b>Principles of Database Design</b> : [17.3/20]</li>
                    <li><b>Data Storage &amp; Retrieval	</b> : [17.25/20]</li>
                    <li><b>Software Engineering (I)</b> : [17.5/20]</li>
                    <li><b>Operating Systems Design</b> : [19.7/20]</li>
                    <li><b>Design of Programming Language</b> : [16.5/20]</li>
                    <li><b>Computer Architecture</b> : [17.5/20]</li>
                    <li><b>Data Structure &amp; Algorithms</b> : [18.8/20]</li>
                    <li><b>Advanced Computer Programming</b> : [17.5/20]</li>
                    <li><b>Principles of Computer &amp; Programing</b> : [17/20]</li>
                    </div>
                  -->
                </div>
                <!--End education-->


                <!--Education-->
                <div class="exp">
                  <div class="hgroup">
                    <h4> M.Sc. Network Engineering&nbsp; [ 2017 - 2019 ]</h4>
                    <h6><i class="fas fa-thumbtack"></i><b class="bold"><a class="gpacolor" href="http://aut.ac.ir/aut/">Amirkabir University of Technology</a></b>, Tehran, Iran (<a href="http://www.usnews.com/education/best-global-universities/amirkabir-university-of-technology-506266" class="gpacolor">Ranked 85th in Computer Science [U.S. News])</a></h6>
                  </div>
                  <p class="tab"><b>GPA</b> of total: <b class="gpacolor">[ 18.77 / 20 ]</b></p>
                  <br>
                  <!--
                    <div class="hgroup tab">
                    <h6 class="tab"><i></i><b>Selected Courses:</b><br>
                    <ul class="two-col-special">
                    <li><b>Foundations of Data Mining</b> : [17.6/20]</li>
                    <li><b>Information Technology Project Management</b> : [19.75/20]</li>
                    <li><b>Engineering Mathematics</b> : [17.6/20]</li>
                    <li><b>Special Topics in Hardware</b> : [19.4/20]</li>
                    <li><b>Internet Engineering</b> : [16.5/20]</li>
                    <li><b>Software Engineering (II)</b> : [16.75/20]</li>
                    <li><b>Principles of Database Design</b> : [17.3/20]</li>
                    <li><b>Data Storage &amp; Retrieval	</b> : [17.25/20]</li>
                    <li><b>Software Engineering (I)</b> : [17.5/20]</li>
                    <li><b>Operating Systems Design</b> : [19.7/20]</li>
                    <li><b>Design of Programming Language</b> : [16.5/20]</li>
                    <li><b>Computer Architecture</b> : [17.5/20]</li>
                    <li><b>Data Structure &amp; Algorithms</b> : [18.8/20]</li>
                    <li><b>Advanced Computer Programming</b> : [17.5/20]</li>
                    <li><b>Principles of Computer &amp; Programing</b> : [17/20]</li>
                    </div>
                  -->
                </div>
                <!--End education-->
                <!--Education-->
                <div class="exp">
                  <div class="hgroup">
                    <h4> B.Sc. Computer Engineering ( Software Engineering )&nbsp; [ 2013 - 2017 ]</h4>
                    <h6><i class="fas fa-thumbtack"></i><b class="bold"><a class="gpacolor" href="http://aut.ac.ir/aut/">Amirkabir University of Technology</a></b>, Tehran, Iran (<a href="http://www.usnews.com/education/best-global-universities/amirkabir-university-of-technology-506266" class="gpacolor">Ranked 85th in Computer Science [U.S. News])</a></h6>
                  </div>
                  <p class="tab"><b>GPA</b> <b class="gpacolor">[ 18.94 / 20 ]</b></p>
                  <br>
                  <!--
                    <div class="hgroup tab">
                    <h6 class="tab"><i></i><b>Selected Courses:</b><br>
                    <ul class="two-col-special">
                    <li><b>Foundations of Data Mining</b> : [17.6/20]</li>
                    <li><b>Information Technology Project Management</b> : [19.75/20]</li>
                    <li><b>Engineering Mathematics</b> : [17.6/20]</li>
                    <li><b>Special Topics in Hardware</b> : [19.4/20]</li>
                    <li><b>Internet Engineering</b> : [16.5/20]</li>
                    <li><b>Software Engineering (II)</b> : [16.75/20]</li>
                    <li><b>Principles of Database Design</b> : [17.3/20]</li>
                    <li><b>Data Storage &amp; Retrieval	</b> : [17.25/20]</li>
                    <li><b>Software Engineering (I)</b> : [17.5/20]</li>
                    <li><b>Operating Systems Design</b> : [19.7/20]</li>
                    <li><b>Design of Programming Language</b> : [16.5/20]</li>
                    <li><b>Computer Architecture</b> : [17.5/20]</li>
                    <li><b>Data Structure &amp; Algorithms</b> : [18.8/20]</li>
                    <li><b>Advanced Computer Programming</b> : [17.5/20]</li>
                    <li><b>Principles of Computer &amp; Programing</b> : [17/20]</li>
                    </div>
                  -->
                </div>
                <!--End education-->
                <!--Education-->
                <div class="exp">
                  <div class="hgroup">
                    <h4>High School Diploma in Mathematics and Physics [ 2009 - 2013 ]</h4>
                    <h6><i class="fas fa-thumbtack"></i><b class="gpacolor"> Energy Atomic High School</b> , Tehran, Iran</h6>
                    <p class="tab"><b>GPA </b><b class="gpacolor">[ 19.45 / 20 ]</b></p>
                  </div>
                </div>
                <!--End education-->
              </div>
              <!--End education holder-->
            </div>
          </div>
          <!--End row-->
        </div>
        <!--End timeline-->
      </div>
    </div>
    <!--End content-->

    <!--Button-->
    <div class="button margTop ofsInTop tCenter">
      <!--Row-->
      <app-divider></app-divider>
      <!--End row-->
    </div>
    <!--End button-->
  </div>
  <!--End education-->
</section>
<!--End education tab-->
