// pages/_app.tsx
import "bootstrap/dist/css/bootstrap.css";
import "@fortawesome/fontawesome-free/css/all.min.css";
import "../styles/base.css";
import "../styles/main.css";

import React from "react";
import Head from "next/head";
import { AppProps } from "next/app";

function MainApp({ Component, pageProps }: AppProps) {
  return (
    <div id="wrapper" className="margLTop margLBottom">
      <Head>
        <title>Parham Alvani</title>
        <link
          rel="icon"
          href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🐼</text></svg>"
        />
      </Head>
      <div className="container">
        <div className="row">
          <div className="col-md-3 left-content">
            <header id="header">
              <div className="main-header">
                <figure className="img-profile">
                  <img src="/me-1.png" alt="Parham Alvani" />
                  <figcaption className="name-profile">
                    <span>PARHAM ALVANI</span>
                  </figcaption>
                </figure>
                <nav id="main-nav" className="main-nav clearfix tabbed">
                  <ul>
                    <li className="nav-item">
                      <a href="/" className="nav-link">
                        <i className="fas fa-user"></i>About Me
                      </a>
                    </li>
                    <li className="nav-item">
                      <a href="/education" className="nav-link">
                        <i className="fas fa-graduation-cap"></i>Education
                      </a>
                    </li>
                    <li className="nav-item">
                      <a href="/experience" className="nav-link">
                        <i className="fas fa-briefcase"></i>Work
                      </a>
                    </li>
                    <li className="nav-item">
                      <a href="/blog" className="nav-link">
                        <i className="fas fa-blog"></i>Blog
                      </a>
                    </li>
                    <li className="nav-item">
                      <a href="/contact" className="nav-link">
                        <i className="fas fa-pen"></i>Contact
                      </a>
                    </li>
                    <li className="nav-item">
                      <a href="/lecture" className="nav-link">
                        <i className="fas fa-book"></i>Lecture
                      </a>
                    </li>
                    <li className="nav-item">
                      <a
                        href="https://1995parham.github.io/stopwatch/"
                        rel="noreferrer"
                        target="_blank"
                        className="nav-link"
                      >
                        <i className="fas fa-stopwatch"></i>Stopwatch
                      </a>
                    </li>
                    <li className="nav-item">
                      <a
                        href="https://1995parham.github.io/MeInBSc/"
                        rel="noreferrer"
                        target="_blank"
                        className="nav-link"
                      >
                        <i className="fas fa-memory"></i>Me in B.Sc.
                      </a>
                    </li>
                  </ul>
                </nav>
              </div>
              <div className="bottom-header bgWhite ofsTSmall ofsBSmall tCenter">
                <ul className="social">
                  <li className="anim">
                    <a
                      href="https://github.com/1995parham"
                      target="_blank"
                      rel="noreferrer"
                    >
                      <i className="fab fa-github"></i>
                    </a>
                  </li>
                  <li className="anim">
                    <a
                      href="http://stackoverflow.com/users/4242097/parham-alvani"
                      target="_blank"
                      rel="noreferrer"
                    >
                      <i className="fab fa-stack-overflow"></i>
                    </a>
                  </li>
                </ul>
                <p>I Have a Dream</p>
              </div>
            </header>
          </div>
          <div className="col-md-9 right-content">
            <Component {...pageProps} />
          </div>
        </div>
      </div>
    </div>
  );
}

export default MainApp;

// src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.less']
})
export class AppComponent {
  title = 'parham';
}

<!--Wrapper-->
<div id="wrapper" class="margLTop  margLBottom">
  <!--Container-->
  <div class="container">
    <div class="row ">
      <!--Left content-->
      <div class="col-md-3 nopr left-content">
        <!--Header-->
        <header id="header">
          <!--Main header-->
          <div class="main-header">
            <!--Profile image-->
            <figure class="img-profile">
              <img src="assets/img/profile.png" alt="Parham Alvani">
              <figcaption class="name-profile"><span>PARHAM ALVANI</span></figcaption>
            </figure>
            <!--End profile image-->
            <!--Main navigation-->
            <nav id="main-nav" class="main-nav clearfix tabbed">
              <ul>
                <li class="nav-item">
                  <a href="#about" class="nav-link active"><i class="icon-user"></i>About ME</a>
                </li>
                <li class="nav-item">
                  <a href="#portfolio" class="nav-link"><i class="icon-graduation-cap"></i>EDUCATION</a>
                </li>
                <li class="nav-item">
                  <a href="#blog" class="nav-link"><i class="icon-briefcase"></i>WORK EXPERIENCE</a>
                </li>
                <li class="nav-item">
                  <a href="#contact" class="nav-link"><i class="icon-pencil"></i>TEACHING</a>
                </li>
              </ul>
            </nav>
            <!--End main navigation-->
          </div>
          <!--End main header-->
        </header>
        <!--End  header-->
      </div>
      <!--End left content-->
      <!--Right content-->
      <div class="col-md-9 right-content">
        <!--About Tab-->
        <section id="about" class="bgWhite ofsInBottom" style="display: block" >
          <!--About -->
          <div class="about">
            <!--Main title-->
            <!--End main title-->
            <!--Content-->
            <div class="content">

              <!--Block content-->
              <div class="block-content margBSmall">

                <div class="profile margBSmall">
                  <h1>PARHAM ALVANI</h1>
                  <h3>Go developer</h3>
                </div>

                <!--Row-->
                <div class="row">
                  <div class="col-md-8">
                    <p>
                      I was born in February 20 1995 in Tehran where I currently live and study
                      Network Engineering at Amirkabir University of Technology.
                    </p>
                    <br>
                    <p>
                      I'm interested in networks and using of it in Internet of Things
                      and I do my best to improve the network connections of things around the world.
                    </p>
                    <br/>
                    <b class="icon-mail" style="font-weight: bold">Email</b> &nbsp;:&nbsp; parham.alvani <b style="font-weight: bold">at</b> gmail <b style="font-weight: bold">dot</b> com
                    <br/>
                    <b class="icon-code" style="font-weight: bold">Website</b> &nbsp;:&nbsp; <a href="https://1995parham.github.io/" target="_blank">https://1995parham.github.io/</a>
                    <br/>
                    <b class="icon-phone" style="font-weight: bold">Phone</b> &nbsp;:&nbsp; <a href="tel://+989390909540" style="color: #777">(+98) 939 0909 540</a>
                  </div>
                  <div class="col-md-4">
                    <b style="font-size:18px; font-weight: bold">Interests:</b>
                    <ul class="bullet">
                      <li>Internet of Things (IoT)</li>
                    </ul>
                    <b style="display: block; font-size:18px; font-weight: bold; margin-top: 30px;">TOEFL iBT score: </b> <b>(95/120)</b>
                    <ul class="bullet">
                      <li>Reading: (28/30)</li>
                      <li>Listening: (27/30)</li>
                      <li>Speaking: (20/30)</li>
                      <li>Writing: (20/30)</li>
                    </ul>
                  </div>
                </div>
                <!--End row-->
              </div>
              <!--End block content-->
            </div>
            <!--End content-->

            <!--Button-->
            <div class="button margTop ofsInTop tCenter">
              <!--Row-->
              <!--End row-->
            </div>
            <!--End button-->
          </div>
          <!--End about-->
        </section>
        <!--End about tab-->
        <!--Education Tab-->
        <section id="education" class="bgWhite ofsInBottom" style="display: none">
          <!--Portfolio -->
          <div class="portfolio">
            <!--Education Main title-->
            <!--End main title-->
            <!--Content-->
            <!--End content-->

            <!--Button-->
            <div class="button margTop ofsInTop tCenter">
              <!--Row-->
              <!--End row-->
            </div>
            <!--End button-->
          </div>
          <!--End portfolio-->
        </section>
        <!--End portfolio tab-->
        <!--Experience Tab-->
        <section id="teaching" class="bgWhite ofsInBottom" style="display: none">
          <!--Blog -->
          <div class="blog">
            <!--Experience Main title-->
            <!--End main title-->
            <!--Content-->
            <!--End content-->

            <!--Button-->
            <div class="button margTop ofsInTop tCenter">
              <!--Row-->
              <!--End row-->
            </div>
            <!--End button-->
          </div>
          <!--End blog-->
        </section>
        <!--End blog tab-->
        <!--Teaching Tab-->
        <section id="work-exp" class="bgWhite ofsInBottom" style="display: none">
          <!--Contact -->
          <div class="contact">
            <!--Experience Main title-->
            <!--End main title-->
            <!--Content-->
            <!--End content-->

            <!--Button-->
            <div class="button margTop ofsInTop tCenter">
              <!--Row-->
              <!--End row-->
            </div>
            <!--End button-->
          </div>
          <!--End contact-->
        </section>
        <!--End contact tab-->
      </div>
      <!--End right content-->
    </div>
    <!--End row-->
  </div>
  <!--End container-->
</div>
<!--End wrapper-->
