// pages/contact.tsx
import Divier from '../components/divider'
import Title from '../components/title'
import React from 'react'

function Contact () {
  return (
    <section id="contact" className="bgWhite ofsInBottom">
      <div className="contact">
        <Title title="Contact Me" />
        <div className="content">
          <div className="block-content margBSmall">
            <div className="row">
              <div className="col-md-8">
                <b style={{ fontWeight: 'bold' }}>
                  <i className="fab fa-google"></i> Email
                </b>
                :&nbsp; parham.alvani <b style={{ fontWeight: 'bold' }}>at</b>{' '}
                gmail <b style={{ fontWeight: 'bold' }}>dot</b> com
                <br />
                <b style={{ fontWeight: 'bold' }}>
                  <i className="fab fa-windows"></i> Email
                </b>
                :&nbsp; parham.alvani <b style={{ fontWeight: 'bold' }}>at</b>{' '}
                hotmail <b style={{ fontWeight: 'bold' }}>dot</b> com
                <br />
                <b style={{ fontWeight: 'bold' }}>
                  <i className="fab fa-yahoo"></i> Email
                </b>
                :&nbsp; parham.alvani <b style={{ fontWeight: 'bold' }}>at</b>{' '}
                yahoo <b style={{ fontWeight: 'bold' }}>dot</b> com
                <br />
                <b style={{ fontWeight: 'bold' }}>
                  <i className="fas fa-university"></i> Email
                </b>
                :&nbsp; parham.alvani <b style={{ fontWeight: 'bold' }}>at</b>{' '}
                aut <b style={{ fontWeight: 'bold' }}>dot</b> ac{' '}
                <b style={{ fontWeight: 'bold' }}>dot</b> ir
                <br />
                <b style={{ fontWeight: 'bold' }}>
                  <i className="fab fa-skype"></i> Skype
                </b>
                :&nbsp; parham.alvani
                <br />
                <b style={{ fontWeight: 'bold' }}>
                  <i className="fas fa-phone"></i> Phone
                </b>
                :&nbsp;{' '}
                <a href="tel://+989390909540" style={{ color: '#777' }}>
                  (+98) 939 0909 540
                </a>
                <Divier />
                <iframe
                  src="https://api.neshan.org/v2/static?key=service.XzI8u04rz0BP19WwNJmjKqEc5gCwtEgqdYzIZEaz&type=dreamy&zoom=17&center=35.731965,51.393047&width=600&height=500&marker=red"
                  width="600"
                  height="450"
                  frameBorder="0"
                  style={{ border: 0, width: '100%' }}
                  allowFullScreen></iframe>
              </div>
              <div className="col-md-4">
                <a
                  href="https://github.com/1995parham.key"
                  target="_blank"
                  role="button"
                  rel="noreferrer"
                  className="btn btn-outline-dark">
                  Public Keys
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}

export default Contact

// src/app/sections/contact/contact.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-contact',
  templateUrl: './contact.component.html',
  styleUrls: ['./contact.component.less']
})
export class ContactComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}

<!--Contact Tab-->
<section id="contact" class="bgWhite ofsInBottom">
  <!--Contact -->
  <div class="contact">
    <!--Main title-->
    <div class="main-title"><h1>Contact Me</h1> <div class="divider"><div data-svg-drawing="yes" class="zigzag large clearfix "><svg xml:space="preserve" viewBox="0 0 69.172 14.975" width="37" height="28" y="0px" x="0px" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" version="1.1"><path d="M1.357,12.26 10.807,2.81 20.328,12.332
    29.781,2.879 39.223,12.321 48.754,2.79 58.286,12.321 67.815,2.793 " style="stroke-dasharray: 93.9851, 93.9851; stroke-dashoffset: 0;"></path></svg></div></div></div>
    <!--End main title-->
    <!--Content-->
    <div class="content">

      <!--Block content-->
      <div class="block-content margBSmall">

        <!--Row-->
        <div class="row">
          <div class="col-md-8">
            <b style="font-weight: bold"><i class="fab fa-google"></i> Email</b>:&nbsp; parham.alvani <b style="font-weight: bold">at</b> gmail <b style="font-weight: bold">dot</b> com
            <br/>
            <b style="font-weight: bold"><i class="fab fa-windows"></i> Email</b>:&nbsp; parham.alvani <b style="font-weight: bold">at</b> hotmail <b style="font-weight: bold">dot</b> com
            <br/>
            <b style="font-weight: bold"><i class="fab fa-yahoo"></i> Email</b>:&nbsp; parham.alvani <b style="font-weight: bold">at</b> yahoo <b style="font-weight: bold">dot</b> com
            <br/>
            <b style="font-weight: bold"><i class="fas fa-university"></i> Email</b>:&nbsp; parham.alvani <b style="font-weight: bold">at</b> aut <b style="font-weight: bold">dot</b> ac <b style="font-weight: bold">dot</b> ir
            <br/>
            <b style="font-weight: bold"><i class="fab fa-skype"></i> Skype</b>:&nbsp; parham.alvani
            <br/>
            <b style="font-weight: bold"><i class="fas fa-phone"></i> Phone</b>:&nbsp; <a href="tel://+989390909540" style="color: #777">(+98) 939 0909 540</a>
            <app-divider></app-divider>
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1619.3816381224674!2d51.39193202301899!3d35.73203999512105!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zMzXCsDQzJzU1LjMiTiA1McKwMjMnMzQuOSJF!5e0!3m2!1sen!2sru!4v1547934894981" width="600" height="450" frameborder="0" style="border:0; width: 100%;" allowfullscreen></iframe>
          </div>
          <div class="col-md-4">
            <a href="https://api.github.com/users/1995parham/keys" target="_blank" role="button" class="btn btn-outline-dark">Public Keys</a>
          </div>
        </div>
        <!--End row-->
      </div>
      <!--End block content-->
    </div>
    <!--End content-->
  </div>
  <!--End contact-->
</section>
<!--End contact tab-->
